# Generated by Django 5.2.18 on 2026-10-07 14:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500, validators=[django.core.validators.URLValidator(schemes=['https'])]),
        ),
    ]
